# Generated by Django 5.2.6 on 2025-09-27 11:02

import django.core.validators
from django.db import migrations, models

import img.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        storage=img.models.ImageFileS3Storage,
                        upload_to=img.models.get_image_s3_file_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "webp",
                                    "bmp",
                                ]
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
